export EDITOR="nvim"
export PATH="${HOME}/.local/bin:${PATH}"
export WORKSPACE="${HOME}/Desktop"

alias a="ag --number"
alias f="fdfind"
alias fd="fdfind"
alias g="grep --recursive --line-number --color --initial-tab"
alias t="tree -C"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

# export EDITOR="emacsclient -tc"
# alias emacs="emacsclient -tc"
# alias e="emacsclient -tc"

# If the shell is not running on a ssh connection, create a new tmux session.
[ -z "${SSH_CLIENT}" ] \
  && [ -z "${SSH_TTY}" ] \
  && command -v tmux &> /dev/null \
  && [ -z "${TMUX}" ] \
  && tmux new

