# If this shell is not running interactively, do not process this script.
case $- in
	*i*) ;;
	*) return ;;
esac

export PATH="$HOME/Apps/bin:$HOME/.local/bin:$PATH"
export TERM="xterm-256color"

alias g="grep"

# Configurations for neovim.
export EDITOR="nvim"
alias vim="nvim"
alias vi="nvim"
alias v="nvim"

# Configurations for emacs.
#export EDITOR="emacsclient -tc"
#alias emacs="emacsclient -tc"
#alias e="emacsclies -tc"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="candy"
plugins=()
source "$ZSH/oh-my-zsh.sh"

# If shell is not running under ssh connection, create new tmux session.
[ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ] &&
	command -v tmux &> /dev/null && [ -z "$TMUX" ] &&
		tmux new
