# If this shell is not running interactively, just return.
case $- in
    *i*) ;;
    *) return ;;
esac

export PATH="${HOME}/.local/bin:${PATH}"
export TERM="xterm-256color"
export EDITOR="nvim"

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias g="grep"

# export EDITOR="emacsclient -tc"
# alias emacs="emacsclient -tc"
# alias e="emacsclies -tc"

export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="candy"
plugins=()
source "${ZSH}/oh-my-zsh.sh"

# If shell is not running under ssh connection, create new tmux session.
[ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ] &&
    command -v tmux &> /dev/null && [ -z "$TMUX" ] &&
        tmux new

