# If this shell is not running interactively, do not process this script.
case $- in
    *i*) ;;
    *) return ;;
esac

export PATH="$HOME/Apps/bin:$HOME/.local/bin:$PATH"
export TERM="xterm-256color"
export EDITOR="nvim"

# emacs
#export EDITOR="emacsclient -tc"
#alias emacs="emacsclient -tc"
#alias e="emacsclient -tc"

alias g="grep"
alias v="nvim"
alias vi="nvim"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="candy"
plugins=()
source "$ZSH/oh-my-zsh.sh"

command -v tmux &> /dev/null && [ -z $TMUX ] && tmux new
