#!/bin/bash
set -o errexit -o errtrace -o nounset -o pipefail

export SCRIPT_ROOT_DIR="${PWD}"
source "${SCRIPT_ROOT_DIR}"/lib/common.sh

if [[ -f "/etc/os-release" ]]; then
  source "/etc/os-release"
elif [[ -f "/usr/lib/os-release" ]]; then
  source "/usr/lib/os-release"
else
  error "Can't find the os-release file"
fi

case "${NAME}" in
  "Ubuntu")
    echo "Ubuntu system detected."
    ./distro/ubuntu.sh
    ;;
  "openSUSE Tumbleweed" | "openSUSE Leap")
    echo "openSUSE system detected."
    ./distro/opensuse.sh
    ;;
  *)
    error "Unknown system detected."
    ;;
esac
