# If this shell is not running interactively, just return.
case $- in
  *i*) ;;
  *) return ;;
esac

export WORKSPACE="${HOME}/Desktop"
export EDITOR="nvim"
export PATH="${HOME}/.local/bin:${PATH}"
export TERM="xterm-256color"

alias a="ag --number"
alias g="grep"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

# export EDITOR="emacsclient -tc"
# alias emacs="emacsclient -tc"
# alias e="emacsclies -tc"

export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="candy"
plugins=(zsh-syntax-highlighting zsh-autosuggestions)
source "${ZSH}/oh-my-zsh.sh"

# If the shell is not running on a ssh connection, create a new tmux session.
[ -z "${SSH_CLIENT}" ] \
  && [ -z "${SSH_TTY}" ] \
  && command -v tmux &> /dev/null \
  && [ -z "${TMUX}" ] \
  && tmux new

