# If not running interactively, don't do anything!
[[ $- != *i* ]] && return

export EDITOR="nvim"
export PATH="~/.local/bin:${PATH}"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="candy"
plugins=(git)
source $ZSH/oh-my-zsh.sh

