# If not running interactively, don't do anything!
[[ $- != *i* ]] && return

export EDITOR="nvim"
export PATH="~/.local/bin:${PATH}"

alias rg="grep --recursive --line-number --color"
alias g="grep --line-number --color"
alias sc="systemctl"
alias jc="journalctl"
