# If not running interactively, don't do anything!
[[ $- != *i* ]] && return

export EDITOR="nvim"
export PATH="${HOME}/.local/bin:${PATH}"

alias g="grep --recursive --line-number --color --initial-tab"
